version: "3"

services:

  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: docker-compose-php-apache-oracle-client
    volumes: 
      - .:/var/www/html
    ports:
      - 8080:80